name: run_workflow
on:
  push:
    branches: 
      - main
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world
        run: echo GHACTIONS
      - name: node
        run: node --version
      - name: npm
        run: npm --version
      - name: npm install
        run: npm install
